### ISSUE TITLE
Error in step05

### ISSUE THREAD

**Issue by LinduniR** [Chester75321/GenEpi#5]
Hi,

I successfully run the GenEpi up to step 04 and getting an error in step 05 as below.

_**Traceback (most recent call last):
  File "/home/n10398406/PD_Data/GenEpi_PD/Trial_chr21_gen/GenEpiL21/bin/GenEpi", line 8, in <module>
    sys.exit(main())
  File "/home/n10398406/PD_Data/GenEpi_PD/Trial_chr21_gen/GenEpiL21/lib/python3.7/site-packages/genepi/GenEpi.py", line 209, in main
    float_score_train, float_score_test = CrossGeneEpistasisLogistic(os.path.join(str_outputFilePath, "singleGeneResult"), str_inputFileName_phenotype, int_kOfKFold=int(args.k), int_nJobs=1)
TypeError: cannot unpack non-iterable float object**_

What can I do to get rid of this error? Really appreciated if you could help me.
Thank you.

Linduni

**Comment by Chester75321** [comment]
Hi Linduni,

Sorry for the late response. The error happened because there were no SNPs
selected in step5. Please check the files in the singleGeneResult folder,
which are the output of step4. In the *_Result.csv, I guess that the
chi-square p-values of the selected features were not significant enough
(log10(p-value) < 5) for further step. And, thanks for the feedback, the
GenEpi 2.0.10 will send you a warning message for this situation instead of
the type error.

Best,
Chester

LinduniR <notifications@github.com> 於 2020年7月13日 週一 下午7:08寫道：

**Comment by LinduniR** [comment]
Hi Chester,

Thank you for your reply. I successfully run the GenEpi and got results for my data. Thank you for your support so far.

I have few questions regarding the output files.

1.In crossGeneResult folder has file with the .pkl extension. I tried to open it using pickle.load(), but it didn't work. Any suggestions?
2. In CrossGeneResult folder has Result.csv file. In that file there is one extra column (singleGene Score) which is not mentioned in the GenEpi documents. Following is the headings and few rows of Results.csv file. Would like to know what SingleGene Score is?
rsid    weight  chi-square_log_p-value  odds_ratio      genotype_frequency      geneSymbol      singleGeneScore
7:21733475:G:A_BB*7:21758045:T:G_AA     -0.28357        5.424037874     0.750207331     0.13234596      DNAH11  0.554608558
4:852659:T:G_BB*4:906131:C:G_AA 0.081056        6.402381867     1.417004049     0.100256337     GAK     0.447900467
4:906131:C:G_AA*4:921733:C:A_BB 0.040279        6.328296421     1.413615654     0.100351277     GAK     0.447900467
17:43543830:T:C_AB*17:43548778:G:C_AB   0.026573        5.256035392     1.260087236     0.298965157     PLEKHM1 0.594378819
17:43548778:G:C_AB*17:43558092:C:T_BB   0.016115        5.144651981     1.256275831     0.303902022     PLEKHM1 0.594378819
17:43548778:G:C_AB*17:43564222:T:G_BB   0.02174 5.144651981     1.256275831     0.303902022     PLEKHM1 0.594378819
4:939087:C:T_AA*4:951179:G:A_BB 0.014799        6.522435183     1.43095898      0.09598405      TMEM175 0.484405966
4:939113:G:A_AB*4:948640:G:A_BB 0.180206        5.177499006     1.367560108     0.097218266     TMEM175 0.484405966

I'm looking forward to hearing from you about the above mentioned questions.
Thank you.
Linduni
________________________________
