### ISSUE TITLE
ModuleNotFoundError in randomised_11.py

### ISSUE THREAD

**Issue by rainajia** [Chester75321/GenEpi#9]
Hi, 
I keep getting this error below. All the "sklearn.module" in the "randomized_l1.py file" cannot be loaded (ModuleNotFounderror)

Is it because there is a circular dependency somewhere?

```
(YOUR_PYTHON) [yrj21@login-e-9 GenEpi]$ GenEpi
Traceback (most recent call last):
  File "path/bin/GenEpi", line 5, in <module>
    from genepi.GenEpi import main
  File "path/lib/python3.6/site-packages/genepi/__init__.py", line 15, in <module>    from .step4_singleGeneEpistasis_Logistic import SingleGeneEpistasisLogistic
  File "path/python3.6/site-packages/genepi/step4_singleGeneEpistasis_Logistic.py", line 34, in <module>
    from genepi.tools import randomized_l1
  File "path/python3.6/site-packages/genepi/tools/__init__.py", line 9, in <module>
    from . import randomized_l1
  File "path/python3.6/site-packages/genepi/tools/randomized_l1.py", line 24, in <module>
    from sklearn.linear_model.base import _preprocess_data
ModuleNotFoundError: No module named 'sklearn.linear_model.base'
```

**Comment by rainajia** [comment]
This has been solved using a lower version of scikit-learn( 0.21.2)
